[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "https://paperfrogs.netlify.app/*"
  to = "https://paperfrogs.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://testpper.netlify.app/*"
  to = "https://paperfrogs.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  NODE_VERSION = "20"
